#!/bin/bash

# This script was generated by Masgent to update VASP input files and submit jobs.
# After modifying the template files (INCAR_temp, KPOINTS_temp, POTCAR_temp,
# and submit_temp.sh, if present), run:
#   bash ./RUN_ME.sh

# Update VASP inputs in each folder
for d in */; do
    cp POTCAR_temp  "$d/POTCAR"

    cp INCAR_temp  "$d/INCAR"

done

# Update submit script and submit jobs in each folder
for d in */; do
    cp submit_temp.sh  "$d/submit.sh"
    chmod +x "$d/submit.sh"
    cd "$d"
    sbatch submit.sh
    cd ..
done
