#!/bin/bash
#SBATCH -N 1
#SBATCH -n 4
#SBATCH -t 12:00:00
#SBATCH -p short
#SBATCH -C 6767P|6254|EPYC-9654|H100|H200|V100|L40S
#SBATCH --job-name=masgent_job
#SBATCH --output=masgent_job.out
#SBATCH --error=masgent_job.err

# This Slurm script was generated by Masgent, customize as needed.

time srun --mpi=pmi2 vasp_std > vasp.out
