# !/usr/bin/env python3

import os, warnings, random
from dotenv import load_dotenv
from ase.io import read, write
from mp_api.client import MPRester
from pymatgen.core import Structure
from pymatgen.io.vasp import Poscar, Kpoints
from pymatgen.io.vasp.sets import (
    MPStaticSet, 
    MPRelaxSet, 
    MPNonSCFSet, 
    MPScanRelaxSet, 
    MPScanStaticSet,
    MPMDSet, 
    )

from masgent import schemas
from masgent.utils import (
    os_path_setup, 
    write_comments,
    color_print,
    ask_for_mp_api_key,
    validate_mp_api_key,
    )

# Do not show warnings
warnings.filterwarnings('ignore')

# Track whether Materials Project key has been checked during this process
_mp_key_checked = False

def generate_vasp_poscar(input: schemas.GenerateVaspPoscarSchema) -> str:
    '''
    Generate VASP POSCAR file from user inputs or from Materials Project database.
    '''
    color_print(f'[Debug: Function Calling] generate_vasp_poscar with input: {input}', 'green')
    
    formula = input.formula

    try:
        base_dir, runs_dir, runs_timestamp_dir, output_dir = os_path_setup()

        # Ensure Materials Project API key exists and validate it only once per process
        load_dotenv(dotenv_path='.env')

        global _mp_key_checked
        if not _mp_key_checked:
            if 'MP_API_KEY' not in os.environ:
                ask_for_mp_api_key()
            else:
                color_print('[Info] Materials Project API key found in environment.\n', 'green')
                validate_mp_api_key(os.environ['MP_API_KEY'])
            _mp_key_checked = True
        
        with MPRester() as mpr:
            docs = mpr.materials.summary.search(formula=formula)
            if not docs:
                return f'\nNo materials found in Materials Project database for formula: {formula}'
            
            mid = docs[0].material_id   # pick the first match
            structure = mpr.get_structure_by_material_id(mid)
            poscar = Poscar(structure)

        # Write POSCAR file to the timestamped run directory
        poscar.write_file(os.path.join(runs_timestamp_dir, 'POSCAR'), direct=True)
        # Also write to the main target directory for easy access
        poscar.write_file(os.path.join(output_dir, 'POSCAR'), direct=True)

        comments = f'# Generated by Masgent AI from Materials Project entry {mid}.'
        write_comments(os.path.join(output_dir, 'POSCAR'), 'poscar', comments)

        return f'\nUpdated POSCAR in {output_dir}.'

    except Exception as e:
        return f'\nPOSCAR generation failed: {str(e)}'
    
def generate_vasp_inputs_from_poscar(input: schemas.GenerateVaspInputsFromPoscar) -> str:
    '''
    Generate VASP input files (INCAR, KPOINTS, POTCAR) using pymatgen input sets.
    '''
    color_print(f'[Debug: Function Calling] generate_vasp_inputs_from_poscar with input: {input}', 'green')
    
    poscar_path = input.poscar_path
    vasp_input_sets = input.vasp_input_sets

    VIS_MAP = {
        'MPRelaxSet': MPRelaxSet,
        'MPStaticSet': MPStaticSet,
        'MPNonSCFSet': MPNonSCFSet,
        'MPScanRelaxSet': MPScanRelaxSet,
        'MPScanStaticSet': MPScanStaticSet,
        'MPMDSet': MPMDSet,
    }
    vis_class = VIS_MAP[vasp_input_sets]

    try:
        base_dir, runs_dir, runs_timestamp_dir, output_dir = os_path_setup()
        
        structure = Structure.from_file(poscar_path)
        vis = vis_class(structure)

        # Write INCAR and POSCAR to the timestamped run directory
        vis.incar.write_file(os.path.join(runs_timestamp_dir, 'INCAR'))
        vis.poscar.write_file(os.path.join(runs_timestamp_dir, 'POSCAR'), direct=True)
        # Also write to the main target directory for easy access
        vis.incar.write_file(os.path.join(output_dir, 'INCAR'))
        vis.poscar.write_file(os.path.join(output_dir, 'POSCAR'), direct=True)
        vis.kpoints.write_file(os.path.join(output_dir, 'KPOINTS'))
        vis.potcar.write_file(os.path.join(output_dir, 'POTCAR'))

        incar_comments = f'# Generated by Masgent AI using {vasp_input_sets} set provided by Materials Project.'
        write_comments(os.path.join(output_dir, 'INCAR'), 'incar', incar_comments)
        kpoints_comments = f'# Generated by Masgent AI using {vasp_input_sets} set provided by Materials Project.'
        write_comments(os.path.join(output_dir, 'KPOINTS'), 'kpoints', kpoints_comments)
        poscar_comments = f'# Generated by Masgent AI using {vasp_input_sets} set provided by Materials Project.'
        write_comments(os.path.join(output_dir, 'POSCAR'), 'poscar', poscar_comments)
        
        return f'\nUpdated VASP input files based on {vasp_input_sets} in {output_dir}.'
    
    except Exception as e:
        return f'\nVASP input files generation failed: {str(e)}'
    
def convert_structure_format(input: schemas.ConvertStructureFormatSchema) -> str:
    '''
    Convert structure files between different formats (CIF, POSCAR, XYZ).
    '''
    color_print(f'[Debug: Function Calling] convert_structure_format with input: {input}', 'green')
    
    input_path = input.input_path
    input_format = input.input_format
    output_format = input.output_format
    
    format_map = {
        "POSCAR": "vasp",
        "CIF": "cif",
        "XYZ": "xyz"
    }

    try:
        base_dir, runs_dir, runs_timestamp_dir, output_dir = os_path_setup()
        
        atoms = read(input_path, format=format_map[input_format])
        filename_wo_ext = os.path.splitext(os.path.basename(input_path))[0]
        output_path = os.path.join(output_dir, f'{filename_wo_ext}.{output_format.lower()}')
        write(output_path, atoms, format=format_map[output_format])

        return f'\nConverted structure saved to {output_path}.'
    
    except Exception as e:
        return f'\nStructure conversion failed: {str(e)}'
    
def convert_poscar_coordinates(input: schemas.ConvertPoscarCoordinatesSchema) -> str:
    '''
    Convert POSCAR between direct and cartesian coordinates.
    '''
    color_print(f'[Debug: Function Calling] convert_poscar_coordinates with input: {input}', 'green')
    
    poscar_path = input.poscar_path
    to_cartesian = input.to_cartesian

    try:
        base_dir, runs_dir, runs_timestamp_dir, output_dir = os_path_setup()
        
        structure = Structure.from_file(poscar_path)
        poscar = Poscar(structure)

        # Write converted POSCAR to the timestamped run directory
        poscar.write_file(os.path.join(runs_timestamp_dir, 'POSCAR'), direct=not to_cartesian)
        # Also write to the main target directory for easy access
        poscar.write_file(os.path.join(output_dir, 'POSCAR'), direct=not to_cartesian)

        coord_type = 'Cartesian' if to_cartesian else 'Direct'

        comments = f'# Generated by Masgent AI converted to {coord_type} coordinates.'
        write_comments(os.path.join(output_dir, 'POSCAR'), 'poscar', comments)

        return f'\nConverted POSCAR to {coord_type} coordinates in {output_dir}.'

    except Exception as e:
        return f'\nPOSCAR coordinate conversion failed: {str(e)}'
    
def customize_vasp_kpoints_with_accuracy(input: schemas.CustomizeVaspKpointsWithAccuracy) -> str:
    '''
    Customize VASP KPOINTS from POSCAR with specified accuracy level.
    '''
    color_print(f'[Debug: Function Calling] customize_vasp_kpoints_with_accuracy with input: {input}', 'green')
    
    poscar_path = input.poscar_path
    accuracy_level = input.accuracy_level
    
    DENSITY_MAP = {
        'Low': 1000,
        'Medium': 3000,
        'High': 5000,
    }
    kppa = DENSITY_MAP[accuracy_level]

    try:
        base_dir, runs_dir, runs_timestamp_dir, output_dir = os_path_setup()
        
        structure = Structure.from_file(poscar_path)
        kpoints = Kpoints.automatic_density(structure, kppa=kppa)

        # Write KPOINTS to the timestamped run directory
        kpoints.write_file(os.path.join(runs_timestamp_dir, 'KPOINTS'))
        # Also write to the main target directory for easy access
        kpoints.write_file(os.path.join(output_dir, 'KPOINTS'))

        comments = f'# Generated by Masgent AI with {accuracy_level} accuracy (Grid Density = {kppa} / number of atoms)'
        write_comments(os.path.join(output_dir, 'KPOINTS'), 'kpoints', comments)
        
        return f'\nUpdated KPOINTS with {accuracy_level} accuracy in {output_dir}.'

    except Exception as e:
        return f'\nVASP KPOINTS generation failed: {str(e)}'
    
def generate_vasp_poscar_with_defects(input: schemas.GenerateVaspPoscarWithDefects) -> str:
    '''
    Generate VASP POSCAR with defects: vacancies, interstitials, substitutions.
    '''
    color_print(f'[Debug: Function Calling] generate_vasp_poscar_with_defects with input: {input}', 'green')

    poscar_path = input.poscar_path
    defect_type = input.defect_type
    original_element = input.original_element
    defect_element = input.defect_element
    defect_amount = input.defect_amount

    try:
        base_dir, runs_dir, runs_timestamp_dir, output_dir = os_path_setup()
        
        atoms = read(poscar_path, format='vasp')

        if defect_type == 'vacancy' or defect_type == 'substitution':
            all_indices = [i for i, atom in enumerate(atoms) if atom.symbol == original_element]
            if isinstance(defect_amount, float):
                num_defects = max(1, int(defect_amount * len(all_indices)))
            elif isinstance(defect_amount, int):
                num_defects = defect_amount
        elif defect_type == 'interstitial':
            all_indices = list(range(len(atoms)))
            if isinstance(defect_amount, float):
                num_defects = max(1, int(defect_amount * len(all_indices)))
            elif isinstance(defect_amount, int):
                num_defects = defect_amount

        if defect_type == 'vacancy':
            vacancy_indices = random.sample(all_indices, num_defects)
            del atoms[vacancy_indices]
        elif defect_type == 'substitution':
            substitution_indices = random.sample(all_indices, num_defects)
            for i in substitution_indices:
                atoms[i].symbol = defect_element
        elif defect_type == 'interstitial':
            interstitial_positions = []
            for _ in range(num_defects):
                pos = [random.uniform(0, 1) for _ in range(3)]
                interstitial_positions.append(pos)
            for pos in interstitial_positions:
                cart = atoms.get_cell() @ pos
                atoms.append(defect_element)
                atoms[-1].position = cart

        output_poscar_path = os.path.join(output_dir, f'POSCAR_{defect_type}.vasp')
        write(output_poscar_path, atoms, format='vasp', direct=True, sort=True)

        comments = f'# Generated by Masgent AI with {defect_type} defect, be careful to verify structure.'
        write_comments(output_poscar_path, 'poscar', comments)

        return f'\nGenerated POSCAR with {defect_type} defects in {output_poscar_path}.'
    
    except Exception as e:
        return f'\nVASP POSCAR defect generation failed: {str(e)}'
    