# !/usr/bin/env python3

import os, sys, datetime, time
import numpy as np
from scipy.optimize import curve_fit
from pathlib import Path
from colorama import Fore, Style
from mp_api.client import MPRester
from openai import OpenAI
from importlib.metadata import version, PackageNotFoundError

def eos_func(volume, a, b, c, d):
    energy = a + b * volume**(-2/3) + c * volume**(-4/3) + d * volume**(-2)
    return energy

def fit_eos(volumes, energies):
    volumes_fit = np.linspace(min(volumes) * 0.99, max(volumes) * 1.01, 100)
    popt, pcov = curve_fit(eos_func, volumes, energies)
    energies_fit = eos_func(volumes_fit, *popt)
    return volumes_fit, energies_fit

def list_files_in_dir(dir):
    '''List all files in a directory and its subdirectories.'''
    base_dir = os.environ.get('MASGENT_SESSION_RUNS_DIR')
    all_files = []
    for root, dirs, files in os.walk(dir):
        for file in files:
            all_files.append(os.path.join(base_dir, file))
    return all_files

def start_new_session():
    '''Set up a new session runs directory.'''
    base_dir = os.getcwd()
    main_dir = os.path.join(base_dir, 'masgent_projects')
    os.makedirs(main_dir, exist_ok=True)
    
    # Create a new runs directory with timestamp
    timestamp = datetime.datetime.now().strftime('%Y%m%d%H%M%S')
    runs_dir = os.path.join(main_dir, f'runs_{timestamp}')
    if not os.path.exists(runs_dir):
        os.makedirs(runs_dir, exist_ok=True)
    else:
        # Rare collision case, wait a second and try again
        time.sleep(1)
        timestamp = datetime.datetime.now().strftime('%Y%m%d%H%M%S')
        runs_dir = os.path.join(main_dir, f'runs_{timestamp}')
        os.makedirs(runs_dir, exist_ok=True)

    os.environ['MASGENT_SESSION_RUNS_DIR'] = runs_dir

def global_commands():
    return [
        '',
        'AI    ->  Chat with the Masgent AI',
        'New   ->  Start a new session',
        'Back  ->  Return to previous menu',
        'Main  ->  Return to main menu',
        'Help  ->  Show available functions',
        'Exit  ->  Quit the Masgent',
    ]

def write_comments(file, file_type, comments):
    with open(file, 'r') as f:
        lines = f.readlines()

    if file_type.lower() in {'poscar', 'kpoints'}:
        lines[0] = comments + '\n'
    
    elif file_type.lower() in {'incar'}:
        lines.insert(0, f'{comments}\n')
    
    with open(file, 'w') as f:
        f.writelines(lines)

def generate_batch_script():
    '''
    Generate batch script for HPC job submission.
    '''
    scripts = '''#!/bin/bash

# This Slurm batch was generated by Masgent, customize as needed.

# 1. Create submit.sh scripts inside each folder
for d in */; do
    cat > "${d}/submit.sh" << 'EOF'
#!/bin/bash
#SBATCH --partition=normal
#SBATCH --nodes=1
#SBATCH --ntasks=8
#SBATCH --time=01:00:00
#SBATCH --job-name=masgent_job
#SBATCH --output=masgent_job.out
#SBATCH --error=masgent_job.err

srun vasp_std > vasp.out
EOF

    chmod +x "${d}/submit.sh"
done

# 2. Submit every job
for d in */; do
    sbatch "${d}/submit.sh"
done
'''
    return scripts

def get_color_map():
    return {
        'red': Fore.RED,
        'green': Fore.GREEN,
        'yellow': Fore.YELLOW,
        'blue': Fore.BLUE,
        'magenta': Fore.MAGENTA,
        'cyan': Fore.CYAN,
        'white': Fore.WHITE,
    }

def color_print(text, color='cyan'):
    '''Print text in specified color.'''
    color_map = get_color_map()
    chosen_color = color_map.get(color.lower(), Fore.CYAN)
    print(chosen_color + text + Style.RESET_ALL)

def color_input(text, color='cyan'):
    '''Input prompt in specified color.'''
    color_map = get_color_map()
    chosen_color = color_map.get(color.lower(), Fore.CYAN)
    return input(chosen_color + text + Style.RESET_ALL)

def load_system_prompts():
    # src/masgent/ai_mode/system_prompt.txt
    prompts_path = Path(__file__).resolve().parent / 'ai_mode' / 'system_prompt.txt'
    try:
        return prompts_path.read_text(encoding='utf-8')
    except Exception as e:
        return f'Error loading system prompts: {str(e)}'

def validate_openai_api_key(key):
    try:
        client = OpenAI(api_key=key)
        client.models.list()
        # color_print('[Info] OpenAI API key validated successfully.\n', 'green')
    except Exception as e:
        color_print('[Error] Invalid OpenAI API key. Exiting...\n', 'green')
        sys.exit(1)

def ask_for_openai_api_key():
    key = color_input('Enter your OpenAI API key: ', 'yellow').strip()
    if not key:
        color_print('[Error] OpenAI API key cannot be empty. Exiting...\n', 'green')
        sys.exit(1)
    
    validate_openai_api_key(key)

    os.environ['OPENAI_API_KEY'] = key

    save = color_input('Save this key to .env file for future? (y/n): ', 'yellow').strip().lower()
    base_dir = os.getcwd()
    env_path = os.path.join(base_dir, '.env')
    if save == 'y':
        with open(env_path, 'w') as f:
            f.write(f'OPENAI_API_KEY={key}\n')
        color_print(f'[Info] OpenAI API key saved to {env_path} file.\n', 'green')
    
def validate_mp_api_key(key):
    try:
        with MPRester(key, mute_progress_bars=True) as mpr:
            _ = mpr.materials.search(
                formula='Si',
                fields=['material_id']
            )
        # color_print('[Info] Materials Project API key validated successfully.\n', 'green')
    except Exception as e:
        color_print('[Error] Invalid Materials Project API key. Exiting...\n', 'green')
        sys.exit(1)
    
def ask_for_mp_api_key():
    key = color_input('Enter your Materials Project API key: ', 'yellow').strip()
    if not key:
        color_print('[Error] Materials Project API key cannot be empty. Exiting...\n', 'green')
        sys.exit(1)

    validate_mp_api_key(key)

    os.environ['MP_API_KEY'] = key

    save = color_input('Save this key to .env file for future? (y/n): ', 'yellow').strip().lower()
    base_dir = os.getcwd()
    env_path = os.path.join(base_dir, '.env')
    if save == 'y':
        with open(env_path, 'a') as f:
            f.write(f'MP_API_KEY={key}\n')
        color_print(f'[Info] Materials Project API key saved to {env_path} file.\n', 'green')

def print_banner():
    try:
        pkg_version = version('masgent')
    except PackageNotFoundError:
        pkg_version = 'dev'
    
    ascii_banner = rf'''
╔═════════════════════════════════════════════════════════════════════════╗
║                                                                         ║
║  ███╗   ███╗  █████╗  ███████╗  ██████╗  ███████╗ ███╗   ██╗ ████████╗  ║
║  ████╗ ████║ ██╔══██╗ ██╔════╝ ██╔════╝  ██╔════╝ ████╗  ██║ ╚══██╔══╝  ║
║  ██╔████╔██║ ███████║ ███████╗ ██║  ███╗ █████╗   ██╔██╗ ██║    ██║     ║
║  ██║╚██╔╝██║ ██╔══██║ ╚════██║ ██║   ██║ ██╔══╝   ██║╚██╗██║    ██║     ║
║  ██║ ╚═╝ ██║ ██║  ██║ ███████║ ╚██████╔╝ ███████╗ ██║ ╚████║    ██║     ║
║  ╚═╝     ╚═╝ ╚═╝  ╚═╝ ╚══════╝  ╚═════╝  ╚══════╝ ╚═╝  ╚═══╝    ╚═╝     ║
║                                                                         ║
║                                   MASGENT: Materials Simulation Agent   ║
║                                      Copyright (c) 2025 Guangchen Liu   ║
║                                                                         ║
║  Version:         {pkg_version:<52}  ║
║  Licensed:        MIT License                                           ║
║  Repository:      https://github.com/aguang5241/masgent                 ║
║  Citation:        Liu, G. et al. (2025), DOI:10.XXXX/XXXXX'             ║
║  Contact:         gliu4@wpi.edu                                         ║
║                                                                         ║
╚═════════════════════════════════════════════════════════════════════════╝
    '''
    color_print(ascii_banner, 'yellow')

def clear_and_print_entry_message():
    os.system('cls' if os.name == 'nt' else 'clear')
    msg = f'''
Welcome to Masgent AI — Your Materials Simulations Agent.
---------------------------------------------------------
Current Session Runs Directory: {os.environ["MASGENT_SESSION_RUNS_DIR"]}

Please select from the following options:
'''
    color_print(msg, 'white')

def clear_and_print_banner_and_entry_message():
    os.system('cls' if os.name == 'nt' else 'clear')
    print_banner()
    msg = f'''
Welcome to Masgent — Your Materials Simulation Agent.
---------------------------------------------------------
Current Session Runs Directory: {os.environ["MASGENT_SESSION_RUNS_DIR"]}

Please select from the following options:
'''
    color_print(msg, 'white')

def print_help():
    os.system('cls' if os.name == 'nt' else 'clear')

    content = '''
Masgent - Available Commands and Functions: 
-------------------------------------------
1. Density Functional Theory (DFT) Simulations
  1.1 Structure Preparation & Manipulation
    1.1.1 Generate POSCAR from chemical formula
    1.1.2 Convert POSCAR coordinates (Direct <-> Cartesian)
    1.1.3 Convert structure file formats (CIF, POSCAR, XYZ)
    1.1.4 Generate structures with defects (Vacancies, Interstitials, Substitutions)
    1.1.5 Generate supercells
    1.1.6 Generate Special Quasirandom Structures (SQS)
    1.1.7 Generate surface slabs
    1.1.8 Generate interface structures
  1.2 VASP Input File Preparation
    1.2.1 Prepare full VASP input files (INCAR, KPOINTS, POTCAR, POSCAR)
    1.2.2 Generate INCAR templates (relaxation, static, MD, etc.)
    1.2.3 Generate KPOINTS with specified accuracy
    1.2.4 Generate HPC job submission script
  1.3 Standard VASP Workflows
    1.3.1 Convergence testing (ENCUT, KPOINTS)
    1.3.2 Equation of State (EOS)
    1.3.3 Elastic constants calculations
  1.4 VASP Output Analysis
2. Fast Simulations Using Machine Learning Potentials (MLPs)
  * Supported MLPs:
    2.1 SevenNet
    2.2 CHGNet
  * Implemented Simulations for all MLPs:
    - Single Point Energy Calculation
    - Equation of State (EOS) Calculation
    - Molecular Dynamics Simulation (NVT)
3. Machine Learning Model Training & Evaluation
'''
    color_print(content, "green")

    try:
        while True:
            input = color_input('Type "back" to return: ', 'yellow').strip().lower()
            if input == 'back':
                return
    except KeyboardInterrupt:
        return

